# Generated by Django 5.0.6 on 2024-05-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_date_added_bill_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='iban',
            field=models.CharField(default=1, max_length=34),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashcall',
            name='invoice_status',
            field=models.CharField(choices=[('created', 'Created'), ('validated', 'Validated'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue')], max_length=10),
        ),
    ]
